### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by wcshen** [Poley97/FSTR#1]
Could you please send me the paper pdf of `Fully Sparse Transformer 3-D Detector for LiDAR Point Cloud` ? 
I cannot access it from IEEE.

**Comment by Poley97** [comment]
Sure. Give me your e-mail address and I'll send the paper to you.

**Comment by wcshen** [comment]
my e-mail: 14752276852@163.com Thanks!

**Comment by Poley97** [comment]
An e-mail has been sent to you. Close issue.
