### ISSUE TITLE
About AV2 configuration

### ISSUE THREAD

**Issue by woxihuanjiangguo** [Poley97/FSTR#2]
Hello author, thanks for your great work! May I ask if the configuration for the AV2 dataset will be released? If not, can you please share with me those configs' differences between the AV2 and the nuScenes?

**Comment by Poley97** [comment]
We'll try to release it soon. There are a few differences between these two datasets, for example, detection range, class name, regression dim(av2 doesn't have velocity ground truth), and non-maximum suppressed classes (we use 1x1 sparse max-pooling for ped and cone in nuScenes, and BICYCLE, CONSTRUCTION_CONE, MOTORCYCLE, PEDESTRIAN, STROLLER for AV2).
