### ISSUE TITLE
显存占用？

### ISSUE THREAD

**Issue by xinpuliu** [Poley97/FSTR#3]
作者您好，请问batch per gpu=1的时候，大约每张卡会占多大显存呀？8卡2080ti能训练最优模型吗？谢谢

**Comment by Poley97** [comment]
当BS=2时，FSTR只需要约6GB的显存，BS=1时，FSTR-Large需要约8~8.5GB显存。Xlarge需要较大的显存，训练时间也较长。你可以尝试一下是否可以使用2080ti训练FSTR-Large。
