### ISSUE TITLE
牛

### ISSUE THREAD

**Issue by WenxuanLi-whu** [Poley97/FSTR#4]
老哥，你们是如何进行测试时间增强的，我的模型测试增强效果很差

**Comment by Poley97** [comment]
你可以尝试以[0.95, 1, 1.05]缩放输入，以[+- 25.0, +- 18.75, +- 12.5, +- 6.25, 0]度旋转输入，以及沿[x axis, y axis]翻转输入，以及上述三种变换的排列组合，来产生若干组不同的预测。将输出的Bbox做反变换之后做NMS就可以了

**Comment by WenxuanLi-whu** [comment]
牛，我就双卡3090，玩不来这个。我刷了测试集，比你的FSTR-L高一点，只希望这篇能水出去

**Comment by WenxuanLi-whu** [comment]
删除帖子哈
